# Generated by Django 6.0.1 on 2026-02-06 21:09

import django.db.models.deletion
import django.utils.timezone
import inbox.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_menu_options_menu_sort_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('order', 'Order'), ('purchase_invoice', 'Purchase invoice'), ('receipt', 'Receipt'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('extracting', 'Extracting'), ('ready', 'Ready'), ('converted', 'Converted'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='DKK', max_length=3)),
                ('converted_purchase_invoice_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_documents', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
            ],
        ),
        migrations.CreateModel(
            name='InboxAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=inbox.models.inbox_upload_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('is_primary', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inbox.inboxdocument')),
            ],
        ),
        migrations.CreateModel(
            name='InboxExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='queued', max_length=20)),
                ('provider', models.CharField(db_index=True, default='external', max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='inbox.inboxdocument')),
            ],
        ),
    ]
