# Generated by Django 6.0.1 on 2026-02-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_menu_options_menu_sort_order'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxdocument',
            name='contra_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbox_documents_as_contra', to='core.account'),
        ),
        migrations.AddField(
            model_name='inboxdocument',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbox_documents_as_gl', to='core.account'),
        ),
    ]
