# Generated by Django 6.0.1 on 2026-02-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_menu_options_menu_sort_order'),
        ('inbox', '0002_inboxdocument_contra_account_and_more'),
        ('masterdata', '0003_creditorgroup_isdefault_debtorgroup_isdefault_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxdocument',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.isocurrencycodes'),
        ),
        migrations.AlterField(
            model_name='inboxdocument',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.creditor'),
        ),
    ]
