# Generated by Django 6.0.1 on 2026-02-10 19:42

import django.db.models.deletion
import django.utils.timezone
import inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inbox', '0003_alter_inboxdocument_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=inbox.models.inbox_upload_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type_guess', models.CharField(blank=True, default='', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='InboxAttachment',
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='inbox_attac_content_7ec5eb_idx'),
        ),
    ]
