# Generated by Django 6.0.1 on 2026-01-31 23:58

import django.core.validators
import django.db.models.deletion
import mptt.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccountsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Chart of Accounts Template',
                'verbose_name_plural': 'Chart of Accounts Templates',
                'ordering': ['-valid_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IsoCountryCodes',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alpha_3', models.CharField(blank=True, default='', max_length=3)),
                ('numeric_code', models.CharField(blank=True, default='', max_length=3)),
                ('iso_3166_2', models.CharField(blank=True, default='', max_length=50)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('sub_region', models.CharField(blank=True, default='', max_length=100)),
                ('intermediate_region', models.CharField(blank=True, default='', max_length=100)),
                ('region_code', models.CharField(blank=True, default='', max_length=10)),
                ('sub_region_code', models.CharField(blank=True, default='', max_length=10)),
                ('intermediate_region_code', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'ISO Country Code',
                'verbose_name_plural': 'ISO Country Codes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IsoCurrencyCodes',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('demonym', models.CharField(blank=True, default='', max_length=100)),
                ('iso_num', models.IntegerField(blank=True, null=True)),
                ('iso_digits', models.IntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, default='', max_length=32)),
                ('symbol_native', models.CharField(blank=True, default='', max_length=32)),
                ('major_single', models.CharField(blank=True, default='', max_length=100)),
                ('major_plural', models.CharField(blank=True, default='', max_length=100)),
                ('minor_single', models.CharField(blank=True, default='', max_length=100)),
                ('minor_plural', models.CharField(blank=True, default='', max_length=100)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('num_to_basic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ISO Currency Code',
                'verbose_name_plural': 'ISO Currency Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_postable', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.account')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('default_ap_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('default_ar_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('fx_gain_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('fx_loss_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.isocountrycodes')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.isocurrencycodes')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.entity'),
        ),
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('prefix', models.CharField(blank=True, default='', max_length=50)),
                ('next_number', models.IntegerField(default=1)),
                ('min_width', models.IntegerField(default=1)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='core.entity')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('entity', 'code')},
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='series_purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='series_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='series_sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='series_sales_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='series_sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_entity_admin', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.entity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal group code (derived or slugified)', max_length=50)),
                ('name', models.CharField(help_text="Momsgruppe (e.g. 'Salg', 'Køb fra EU-lande')", max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_groups', to='core.entity')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('entity', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccountsNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('HEADER', 'Header'), ('GROUP', 'Group'), ('ACCOUNT', 'Account')], max_length=20)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.chartofaccountsnode')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.chartofaccountstemplate')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('template', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('entity', 'number')},
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('base', models.CharField(db_index=True, help_text='Base currency (e.g. EUR)', max_length=3)),
                ('quote', models.CharField(db_index=True, help_text='Quote currency (e.g. DKK)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, help_text='1 base = rate * quote', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('source', models.CharField(choices=[('ECB', 'European Central Bank'), ('MANUAL', 'Manual')], default='ECB', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, help_text='Optional. Null = global rate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.entity')),
            ],
            options={
                'ordering': ['-date', 'base', 'quote'],
                'indexes': [models.Index(fields=['date', 'base', 'quote'], name='core_exchan_date_c17353_idx'), models.Index(fields=['entity', 'date'], name='core_exchan_entity__edb964_idx')],
                'unique_together': {('entity', 'date', 'base', 'quote', 'source')},
            },
        ),
        migrations.CreateModel(
            name='VatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('legacy_code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('vat_type', models.CharField(choices=[('SALE', 'Salg'), ('PURCHASE', 'Køb')], default=None, max_length=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='VAT rate (e.g. 0.2500 for 25%)', max_digits=6, null=True)),
                ('deduction_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Deduction rate (1.0 = 100%, 0.6666 = 66.66%)', max_digits=6, null=True)),
                ('deduction_method', models.CharField(blank=True, help_text='Skøn, Pro rata, Arealfordeling, Sektor, etc.', max_length=50)),
                ('reporting_text', models.CharField(blank=True, help_text='Momsangivelse / reporting description', max_length=255)),
                ('dk_only', models.BooleanField(default=False)),
                ('dk_mixed', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('international_mixed', models.BooleanField(default=False)),
                ('special_scheme', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_codes', to='core.entity')),
                ('input_vat_account', models.ForeignKey(blank=True, help_text='Purchase VAT (indgående moms) account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('output_vat_account', models.ForeignKey(blank=True, help_text='Sales VAT (udgående moms) account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='vat_codes', to='core.vatgroup')),
            ],
            options={
                'ordering': ['group__code', 'code'],
                'unique_together': {('entity', 'code')},
            },
        ),
    ]
