# Generated by Django 6.0.1 on 2026-01-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoCountryCodes',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ISO Country Code',
                'verbose_name_plural': 'ISO Country Codes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IsoCurrencyCodes',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ISO Currency Code',
                'verbose_name_plural': 'ISO Currency Codes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(help_text='ISO country code', on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='core.isocountrycodes'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='currency',
            field=models.ForeignKey(help_text='ISO currency code', on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='core.isocurrencycodes'),
        ),
    ]
