# Generated by Django 6.0.1 on 2026-01-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_isocountrycodes_isocurrencycodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccountsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Chart of Accounts Template',
                'verbose_name_plural': 'Chart of Accounts Templates',
                'ordering': ['-valid_from', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='isocurrencycodes',
            options={'ordering': ['code'], 'verbose_name': 'ISO Currency Code', 'verbose_name_plural': 'ISO Currency Codes'},
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='alpha_3',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='intermediate_region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='intermediate_region_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='iso_3166_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='numeric_code',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='region_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='sub_region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='isocountrycodes',
            name='sub_region_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='decimals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='demonym',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='iso_digits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='iso_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='major_plural',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='major_single',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='minor_plural',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='minor_single',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='num_to_basic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='isocurrencycodes',
            name='symbol_native',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='core.isocountrycodes'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='core.isocurrencycodes'),
        ),
        migrations.CreateModel(
            name='ChartOfAccountsNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('HEADER', 'Header'), ('GROUP', 'Group'), ('ACCOUNT', 'Account')], max_length=20)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.chartofaccountsnode')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.chartofaccountstemplate')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('template', 'number')},
            },
        ),
    ]
