# Generated by Django 6.0.1 on 2026-01-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chartofaccountstemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='template_node',
            field=models.ForeignKey(blank=True, help_text='Origin in chart of accounts template', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.chartofaccountsnode'),
        ),
    ]
