# Generated by Django 6.0.1 on 2026-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_template_node'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='jl_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('credit', 0), _connector='OR'), name='jl_not_both_sides'),
        ),
    ]
