# Generated by Django 6.0.1 on 2026-02-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_menu_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['parent_id', 'sort_order', 'menu']},
        ),
        migrations.AddField(
            model_name='menu',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
