# Generated by Django 6.0.1 on 2026-01-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_journalline_jl_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. Billing, Delivery', max_length=50)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, help_text='ISO-2 country code', max_length=2)),
                ('attention', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['country', 'postal_code', 'city', 'line1'],
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DebtorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('days', models.PositiveIntegerField(default=14)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='journalline',
            name='jl_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='journalline',
            name='jl_not_both_sides',
        ),
        migrations.AddField(
            model_name='debtor',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_debtors', to='core.address'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_debtors', to='core.address'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='core.entity'),
        ),
        migrations.AddField(
            model_name='debtorgroup',
            name='ar_account',
            field=models.ForeignKey(help_text='Accounts receivable control account for this group', on_delete=django.db.models.deletion.PROTECT, related_name='debtor_groups_ar', to='core.account'),
        ),
        migrations.AddField(
            model_name='debtorgroup',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_groups', to='core.entity'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to='core.debtorgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='cogs_account',
            field=models.ForeignKey(blank=True, help_text='Overrides group default COGS account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_cogs', to='core.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.entity'),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory_account',
            field=models.ForeignKey(blank=True, help_text='Overrides group default inventory account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_inventory', to='core.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_account',
            field=models.ForeignKey(blank=True, help_text='Overrides group default sales account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_sales', to='core.account'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='default_cogs_account',
            field=models.ForeignKey(blank=True, help_text='Default cost-of-goods-sold account (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_groups_cogs', to='core.account'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='default_inventory_account',
            field=models.ForeignKey(blank=True, help_text='Default inventory/stock account (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_groups_inventory', to='core.account'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='default_sales_account',
            field=models.ForeignKey(help_text='Default revenue account for items in this group', on_delete=django.db.models.deletion.PROTECT, related_name='item_groups_sales', to='core.account'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='core.entity'),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.itemgroup'),
        ),
        migrations.AddField(
            model_name='paymentterms',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='core.entity'),
        ),
        migrations.AddField(
            model_name='debtorgroup',
            name='default_payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debtor_groups_default', to='core.paymentterms'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='payment_terms',
            field=models.ForeignKey(blank=True, help_text='If blank, group default is used', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to='core.paymentterms'),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_codes', to='core.entity'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='default_vat_code',
            field=models.ForeignKey(blank=True, help_text='Default VAT code for sales of items in this group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_groups_default_vat', to='core.vatcode'),
        ),
        migrations.AddField(
            model_name='item',
            name='vat_code',
            field=models.ForeignKey(blank=True, help_text='Overrides group default VAT code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_vat', to='core.vatcode'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentterms',
            unique_together={('entity', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='debtorgroup',
            unique_together={('entity', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='debtor',
            unique_together={('entity', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='vatcode',
            unique_together={('entity', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='itemgroup',
            unique_together={('entity', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('entity', 'sku')},
        ),
    ]
