# Generated by Django 6.0.1 on 2026-01-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_debtor_debtorgroup_item_itemgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vatcode',
            options={'ordering': ['group__code', 'code']},
        ),
        migrations.AddField(
            model_name='vatcode',
            name='deduction_method',
            field=models.CharField(blank=True, help_text='Skøn, Pro rata, Arealfordeling, Sektor, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='deduction_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Deduction rate (1.0 = 100%, 0.6666 = 66.66%)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='dk_mixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='dk_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='international_mixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='legacy_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='reporting_text',
            field=models.CharField(blank=True, help_text='Momsangivelse / reporting description', max_length=255),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='special_scheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='vat_type',
            field=models.CharField(choices=[('SALE', 'Salg'), ('PURCHASE', 'Køb')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='vatcode',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vatcode',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='VAT rate (e.g. 0.2500 for 25%)', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='VatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal group code (derived or slugified)', max_length=50)),
                ('name', models.CharField(help_text="Momsgruppe (e.g. 'Salg', 'Køb fra EU-lande')", max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_groups', to='core.entity')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('entity', 'code')},
            },
        ),
        migrations.AddField(
            model_name='vatcode',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='vat_codes', to='core.vatgroup'),
        ),
    ]
