# Generated by Django 6.0.1 on 2026-01-29 21:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vatcode_options_vatcode_deduction_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('SALES_OFFER', 'Sales Offer'), ('SALES_ORDER', 'Sales Order'), ('SALES_INVOICE', 'Sales Invoice'), ('SALES_CREDIT_NOTE', 'Sales Credit Note'), ('PURCHASE_ORDER', 'Purchase Order'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('PURCHASE_CREDIT_NOTE', 'Purchase Credit Note')], max_length=40)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.isocurrencycodes')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='core.debtor')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.entity')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseCreditNote',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase credit note',
                'verbose_name_plural': 'Purchase credit notes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase invoice',
                'verbose_name_plural': 'Purchase invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='SalesCreditNote',
            fields=[
            ],
            options={
                'verbose_name': 'Sales credit note',
                'verbose_name_plural': 'Sales credit notes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Sales invoice',
                'verbose_name_plural': 'Sales invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='SalesOffer',
            fields=[
            ],
            options={
                'verbose_name': 'Sales offer',
                'verbose_name_plural': 'Sales offers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Sales order',
                'verbose_name_plural': 'Sales orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('SALES_OFFER', 'Sales offer'), ('SALES_ORDER', 'Sales order'), ('SALES_INVOICE', 'Sales invoice'), ('SALES_CREDIT_NOTE', 'Sales credit note'), ('PURCHASE_ORDER', 'Purchase order'), ('PURCHASE_INVOICE', 'Purchase invoice'), ('PURCHASE_CREDIT_NOTE', 'Purchase credit note')], max_length=40)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_statuses', to='core.entity')),
            ],
            options={
                'ordering': ('entity', 'doc_type', 'sort_order', 'code'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Must belong to the same entity and document type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.documentstatus'),
        ),
        migrations.AddConstraint(
            model_name='documentstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('entity', 'doc_type'), name='uniq_default_status_per_entity_and_type'),
        ),
        migrations.AlterUniqueTogether(
            name='documentstatus',
            unique_together={('entity', 'doc_type', 'code')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entity', 'doc_type', 'date'], name='core_docume_entity__3765b2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entity', 'doc_type', 'number'], name='core_docume_entity__15da66_idx'),
        ),
    ]
