# Generated by Django 6.0.1 on 2026-01-29 22:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_document_purchasecreditnote_purchaseinvoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
            ],
            options={
                'ordering': ('document_id', 'line_no', 'id'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='posted_journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_document', to='core.journal'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_ap_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account'),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='input_vat_account',
            field=models.ForeignKey(blank=True, help_text='Purchase VAT (indgående moms) account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account'),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='output_vat_account',
            field=models.ForeignKey(blank=True, help_text='Sales VAT (udgående moms) account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='jl_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit', 0), ('credit', 0), _connector='OR'), name='jl_not_both_sides'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.document'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.item'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='vat_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vatcode'),
        ),
    ]
