# Generated by Django 6.0.1 on 2026-01-29 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documentline_document_posted_at_document_posted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('JOURNAL', 'Journal'), ('DEBTOR', 'Debtor'), ('CREDITOR', 'Creditor'), ('ITEM', 'Item'), ('SALES_OFFER', 'Sales offer'), ('SALES_ORDER', 'Sales order'), ('SALES_INVOICE', 'Sales invoice'), ('SALES_CREDIT_NOTE', 'Sales credit note'), ('PURCHASE_ORDER', 'Purchase order'), ('PURCHASE_INVOICE', 'Purchase invoice'), ('PURCHASE_CREDIT_NOTE', 'Purchase credit note')], max_length=40)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('padding', models.PositiveSmallIntegerField(default=0)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('increment', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='core.entity')),
            ],
        ),
        migrations.AddField(
            model_name='debtorgroup',
            name='number_series',
            field=models.ForeignKey(blank=True, help_text='Override number series for debtors in this group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_purchase_credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_sales_credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_sales_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_series_sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='number_series',
            field=models.ForeignKey(blank=True, help_text='Override number series for items in this group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.numberseries'),
        ),
        migrations.AddIndex(
            model_name='numberseries',
            index=models.Index(fields=['entity', 'purpose', 'is_active'], name='core_number_entity__4ed6fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='numberseries',
            unique_together={('entity', 'code')},
        ),
    ]
