# Generated by Django 6.0.1 on 2026-01-30 00:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_journal_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('base', models.CharField(db_index=True, help_text='Base currency (e.g. EUR)', max_length=3)),
                ('quote', models.CharField(db_index=True, help_text='Quote currency (e.g. DKK)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, help_text='1 base = rate * quote', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('source', models.CharField(choices=[('ECB', 'European Central Bank'), ('MANUAL', 'Manual')], default='ECB', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When the rate was fetched/imported')),
                ('entity', models.ForeignKey(blank=True, help_text='Optional. Null = global rate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.entity')),
            ],
            options={
                'ordering': ['-date', 'base', 'quote'],
                'indexes': [models.Index(fields=['date', 'base', 'quote'], name='core_exchan_date_c17353_idx'), models.Index(fields=['entity', 'date'], name='core_exchan_entity__edb964_idx')],
                'unique_together': {('entity', 'date', 'base', 'quote', 'source')},
            },
        ),
    ]
