# Generated by Django 6.0.1 on 2026-01-31 23:59

import django.db.models.deletion
import django_fsm
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('AR', 'Accounts receivable'), ('AP', 'Accounts payable')], max_length=2)),
                ('original_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('original_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remaining_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remaining_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalJournal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=50, protected=True)),
                ('number', models.CharField(blank=True, default='', max_length=40)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.entity')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical journal',
                'verbose_name_plural': 'historical journals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=50, protected=True)),
                ('number', models.CharField(blank=True, default='', max_length=40)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='core.entity')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('debit_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('debit_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.isocurrencycodes')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
