# Generated by Django 6.0.1 on 2026-01-31 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0002_initial'),
        ('ledger', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openitem',
            name='creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.creditor'),
        ),
        migrations.AddField(
            model_name='openitem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.isocurrencycodes'),
        ),
        migrations.AddField(
            model_name='openitem',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.debtor'),
        ),
        migrations.AddField(
            model_name='openitem',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='core.entity'),
        ),
        migrations.AddField(
            model_name='openitem',
            name='purchase_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.purchasedocument'),
        ),
        migrations.AddField(
            model_name='openitem',
            name='sales_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.salesdocument'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.entity'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='open_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='ledger.openitem'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='ledger.journalline'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['entity', 'state', 'date'], name='ledger_jour_entity__ba0be4_idx'),
        ),
    ]
