# Generated by Django 6.0.1 on 2026-02-03 19:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_settlement_settled_at_settlement_settled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSaldoRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'verbose_name': 'Customer saldo',
                'verbose_name_plural': 'Customer saldo',
                'managed': False,
            },
        ),
    ]
