# Generated by Django 6.0.1 on 2026-02-03 22:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_customersaldorow'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorSaldoRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'verbose_name': 'Creditor saldo',
                'verbose_name_plural': 'Creditor saldo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryOverviewRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('value_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'verbose_name': 'Inventory overview',
                'verbose_name_plural': 'Inventory overview',
                'managed': False,
            },
        ),
    ]
