# Generated by Django 6.0.1 on 2026-02-08 20:52

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_creditorsaldorow_inventoryoverviewrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljournal',
            name='state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', editable=False, max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', editable=False, max_length=50, protected=True),
        ),
    ]
