# Generated by Django 6.0.1 on 2026-01-31 23:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost_base', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_remaining', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('unit_cost_base', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_layers', to='core.entity')),
            ],
        ),
    ]
