# Generated by Django 6.0.1 on 2026-01-31 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0002_initial'),
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylayer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_moves', to='core.entity'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='purchase_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.purchaseline'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='sales_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.salesline'),
        ),
    ]
