# Generated by Django 6.0.1 on 2026-01-31 23:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_groups', to='core.entity')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('entity', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DebtorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('payment_terms_days', models.IntegerField(default=14)),
                ('ar_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_groups', to='core.entity')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('entity', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('cogs_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('default_purchase_vat_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatcode')),
                ('default_sales_vat_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatcode')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='core.entity')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('entity', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_area', models.CharField(choices=[('DK', 'Denmark'), ('EU_B2B', 'EU B2B'), ('EXPORT', 'Export / outside EU'), ('DK_SPECIAL', 'DK special scheme')], default='DK', max_length=20)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='core.entity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditors', to='masterdata.creditorgroup')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('entity', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('vat_area', models.CharField(choices=[('DK', 'Denmark'), ('EU_B2B', 'EU B2B'), ('EXPORT', 'Export / outside EU'), ('DK_SPECIAL', 'DK special scheme')], default='DK', max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='core.entity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to='masterdata.debtorgroup')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('entity', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_stock_item', models.BooleanField(default=True)),
                ('sales_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.entity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masterdata.itemgroup')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('entity', 'number')},
            },
        ),
    ]
