# Generated by Django 6.0.1 on 2026-02-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='EAN-13 barcode (13 digits)', max_length=13, null=True, unique=True),
        ),
    ]
