# Generated by Django 6.0.1 on 2026-02-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_item_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorgroup',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debtorgroup',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
