# Generated by Django 6.0.1 on 2026-01-31 23:59

import django_fsm
import simple_history.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('order', 'Order'), ('invoice', 'Invoice'), ('posted', 'Posted')], default='order', max_length=50, protected=True)),
                ('date', models.DateField()),
                ('order_no', models.CharField(blank=True, default='', max_length=40)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=40)),
                ('total_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical purchase document',
                'verbose_name_plural': 'historical purchase documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalesDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('offer', 'Offer'), ('order', 'Order'), ('invoice', 'Invoice'), ('posted', 'Posted')], default='offer', max_length=50, protected=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('offer_no', models.CharField(blank=True, default='', max_length=40)),
                ('order_no', models.CharField(blank=True, default='', max_length=40)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=40)),
                ('total_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical sales document',
                'verbose_name_plural': 'historical sales documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('order', 'Order'), ('invoice', 'Invoice'), ('posted', 'Posted')], default='order', max_length=50, protected=True)),
                ('date', models.DateField()),
                ('order_no', models.CharField(blank=True, default='', max_length=40)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=40)),
                ('total_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('unit_cost_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('offer', 'Offer'), ('order', 'Order'), ('invoice', 'Invoice'), ('posted', 'Posted')], default='offer', max_length=50, protected=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('offer_no', models.CharField(blank=True, default='', max_length=40)),
                ('order_no', models.CharField(blank=True, default='', max_length=40)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=40)),
                ('total_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('unit_price_tx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
    ]
