# Generated by Django 6.0.1 on 2026-01-31 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        ('ledger', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchasedocument',
            name='creditor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.creditor'),
        ),
        migrations.AddField(
            model_name='historicalpurchasedocument',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.isocurrencycodes'),
        ),
        migrations.AddField(
            model_name='historicalpurchasedocument',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.entity'),
        ),
        migrations.AddField(
            model_name='historicalpurchasedocument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchasedocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchasedocument',
            name='posted_journal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.journal'),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.isocurrencycodes'),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='debtor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.debtor'),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.entity'),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='posted_journal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.journal'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_documents', to='masterdata.creditor'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.isocurrencycodes'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_documents', to='core.entity'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='posted_journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_source', to='ledger.journal'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.purchasedocument',),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.purchasedocument',),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.purchasedocument'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='vat_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vatcode'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.isocurrencycodes'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='masterdata.debtor'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_documents', to='core.entity'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='posted_journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_source', to='ledger.journal'),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.salesdocument',),
        ),
        migrations.CreateModel(
            name='SalesOffer',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Offer',
                'verbose_name_plural': 'Sales Offers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.salesdocument',),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.salesdocument',),
        ),
        migrations.AddField(
            model_name='salesline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.salesdocument'),
        ),
        migrations.AddField(
            model_name='salesline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='salesline',
            name='vat_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vatcode'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['entity', 'state', 'date'], name='documents_p_entity__700eda_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['entity', 'order_no'], name='documents_p_entity__46d598_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['entity', 'invoice_no'], name='documents_p_entity__3da936_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseline',
            unique_together={('document', 'line_no')},
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['entity', 'state', 'date'], name='documents_s_entity__071e03_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['entity', 'offer_no'], name='documents_s_entity__9bf988_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['entity', 'order_no'], name='documents_s_entity__37105a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['entity', 'invoice_no'], name='documents_s_entity__76b1ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesline',
            unique_together={('document', 'line_no')},
        ),
    ]
