# Generated by Django 6.0.1 on 2026-02-02 07:27

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='credited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='credited_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalesdocument',
            name='paid_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='credited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='credited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsalesdocument',
            name='state',
            field=django_fsm.FSMField(choices=[('offer', 'Offer'), ('order', 'Order'), ('invoice', 'Invoice'), ('posted', 'Posted'), ('partly_paid', 'Partly paid'), ('paid', 'Paid'), ('credited', 'Credited')], default='offer', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='state',
            field=django_fsm.FSMField(choices=[('offer', 'Offer'), ('order', 'Order'), ('invoice', 'Invoice'), ('posted', 'Posted'), ('partly_paid', 'Partly paid'), ('paid', 'Paid'), ('credited', 'Credited')], default='offer', max_length=50, protected=True),
        ),
    ]
