"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

APP_LABEL = "core"

def admin_changelist(model: str):
    # model must be lowercase model name, e.g. "vatcode"
    return reverse_lazy(f"admin:{APP_LABEL}_{model}_changelist")

UNFOLD = {
    "SITE_HEADER": "Kingfisher ERP",
    "SITE_TITLE": "Kingfisher ERP",
    "SITE_URL": "/",  # optional: logo link
    "DASHBOARD_CALLBACK": None,  # optional advanced
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,  # only show our curated menu
        "navigation": [
            {
                "title": _("Company & Setup"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": _("Entities"), "icon": "apartment", "link": admin_changelist("entity")},
                    {"title": _("Fiscal years"), "icon": "event", "link": admin_changelist("fiscalyear")},
                    {"title": _("Addresses"), "icon": "home_pin", "link": admin_changelist("address")},
                    {"title": _("Payment terms"), "icon": "schedule", "link": admin_changelist("paymentterms")},
                ],
            },
            {
                "title": _("Finance"),
                "collapsible": True,
                "items": [
                    {"title": _("Accounts"), "icon": "account_balance", "link": admin_changelist("account")},
                    {"title": _("Journals"), "icon": "receipt_long", "link": admin_changelist("journal")},
                ],
            },
            {
                "title": _("VAT"),
                "collapsible": True,
                "items": [
                    {"title": _("VAT groups"), "icon": "folder", "link": admin_changelist("vatgroup")},
                    {"title": _("VAT codes"), "icon": "percent", "link": admin_changelist("vatcode")},
                ],
            },
            {
                "title": _("Sales (AR)"),
                "collapsible": True,
                "items": [
                    {"title": _("Debtor groups"), "icon": "groups", "link": admin_changelist("debtorgroup")},
                    {"title": _("Debtors"), "icon": "person", "link": admin_changelist("debtor")},
                ],
            },
            {
                "title": _("Items"),
                "collapsible": True,
                "items": [
                    {"title": _("Item groups"), "icon": "category", "link": admin_changelist("itemgroup")},
                    {"title": _("Items"), "icon": "inventory_2", "link": admin_changelist("item")},
                ],
            },
            {
                "title": _("Chart of Accounts"),
                "collapsible": True,
                "items": [
                    {"title": _("COA templates"), "icon": "account_tree", "link": admin_changelist("chartofaccountstemplate")},
                ],
            },
            {
                "title": _("Reference data"),
                "collapsible": True,
                "items": [
                    {"title": _("ISO countries"), "icon": "public", "link": admin_changelist("isocountrycodes")},
                    {"title": _("ISO currencies"), "icon": "currency_exchange", "link": admin_changelist("isocurrencycodes")},
                ],
            },
        ],
    },
}








# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-of3d8!931g^lx9m@q%c8)%1#-s0uybxd*f!q5p5=9ef=3gh^7v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', ]


# Application definition

INSTALLED_APPS = [
    "unfold",  # must be before django.contrib.admin
    # optional:
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
