# Generated by Django 6.0.1 on 2026-02-09 22:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_menu_options_menu_sort_order'),
        ('ledger', '0006_alter_historicaljournal_state_alter_journal_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankMatchJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gl_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.journalline')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankrec.bankmatch')),
            ],
        ),
        migrations.AddField(
            model_name='bankmatch',
            name='gl_lines',
            field=models.ManyToManyField(related_name='bank_matches', through='bankrec.BankMatchJournalLine', to='ledger.journalline'),
        ),
        migrations.CreateModel(
            name='BankReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gl_date_from', models.DateField(blank=True, null=True)),
                ('gl_date_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankrec_sessions', to='core.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankmatch',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='bankrec.bankreconciliationsession'),
        ),
        migrations.CreateModel(
            name='BankReconciliationSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default bank setup', max_length=120)),
                ('bank_account_no', models.CharField(blank=True, default='', help_text='IBAN / bankkonto-id (valgfri)', max_length=64)),
                ('amount_tolerance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('date_window_days', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankrec_setups', to='core.entity')),
                ('gl_bank_account', models.ForeignKey(help_text='Finanskonto der repræsenterer bankkontoen', on_delete=django.db.models.deletion.PROTECT, related_name='bankrec_setups', to='core.account')),
            ],
        ),
        migrations.AddField(
            model_name='bankreconciliationsession',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='bankrec.bankreconciliationsetup'),
        ),
        migrations.CreateModel(
            name='BankStatementStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.CharField(max_length=80)),
                ('statement_date_from', models.DateField(blank=True, null=True)),
                ('statement_date_to', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('status', models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('reconciling', 'Reconciling'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_staging_headers', to='core.entity')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staging_headers', to='bankrec.bankreconciliationsetup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankreconciliationsession',
            name='staging',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_session', to='bankrec.bankstatementstaging'),
        ),
        migrations.CreateModel(
            name='BankStatementStagingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_tx_id', models.CharField(max_length=120)),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('text', models.CharField(blank=True, default='', max_length=512)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bankrec.bankstatementstaging')),
            ],
            options={
                'ordering': ['booking_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankMatchBankLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankrec.bankmatch')),
                ('bank_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankrec.bankstatementstagingline')),
            ],
        ),
        migrations.AddField(
            model_name='bankmatch',
            name='bank_lines',
            field=models.ManyToManyField(related_name='bank_matches', through='bankrec.BankMatchBankLine', to='bankrec.bankstatementstagingline'),
        ),
        migrations.AddConstraint(
            model_name='bankmatchjournalline',
            constraint=models.UniqueConstraint(fields=('gl_line',), name='uniq_gl_line_global_match'),
        ),
        migrations.AlterUniqueTogether(
            name='bankmatchjournalline',
            unique_together={('match', 'gl_line')},
        ),
        migrations.AlterUniqueTogether(
            name='bankreconciliationsetup',
            unique_together={('entity', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bankstatementstaging',
            unique_together={('entity', 'statement_id')},
        ),
        migrations.AlterUniqueTogether(
            name='bankstatementstagingline',
            unique_together={('header', 'bank_tx_id')},
        ),
        migrations.AddConstraint(
            model_name='bankmatchbankline',
            constraint=models.UniqueConstraint(fields=('bank_line',), name='uniq_bank_line_global_match'),
        ),
        migrations.AlterUniqueTogether(
            name='bankmatchbankline',
            unique_together={('match', 'bank_line')},
        ),
    ]
